# Generated by Django 2.0.4 on 2018-10-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181023_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='create_date',
            field=models.TextField(blank=True),
        ),
    ]
