# Generated by Django 2.0.4 on 2018-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playlist_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.TextField(max_length=20, null=True)),
                ('commentator', models.CharField(max_length=90)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
