# Generated by Django 2.0.4 on 2018-10-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20181025_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsong',
            name='like',
            field=models.TextField(default='0'),
        ),
    ]
