# Generated by Django 2.0.4 on 2018-10-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_commentsong_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentsongsecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hufupeople', models.CharField(max_length=90)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commentator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to='music.Commentsong')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
