# Generated by Django 2.0.4 on 2018-10-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_commentsongsecond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsongsecond',
            old_name='commentator_id',
            new_name='commentator',
        ),
    ]
