# Generated by Django 2.0.4 on 2018-10-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_commentlikestates'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikestates',
            name='dianzanuser',
            field=models.TextField(default='', max_length=90),
        ),
    ]
