# Generated by Django 2.0.4 on 2018-10-29 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0012_commentlikestates_dianzanuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creategedan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
