# Generated by Django 2.0.4 on 2018-10-29 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20181029_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gedansong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.TextField(max_length=20, null=True)),
                ('music_name', models.TextField(max_length=20, null=True)),
                ('music_albumimg', models.TextField(blank=True)),
                ('music_url', models.TextField(blank=True)),
                ('create_date', models.TextField(blank=True)),
                ('gedan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gedan', to='music.Creategedan')),
            ],
        ),
    ]
