# Generated by Django 2.0.4 on 2018-10-29 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_gedansong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategedan',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
