# Generated by Django 2.0.4 on 2018-10-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20181029_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gedansong',
            name='music_url',
        ),
    ]
