# Generated by Django 2.0.4 on 2018-10-29 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_remove_gedansong_music_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gedansong',
            name='create_date',
        ),
        migrations.AddField(
            model_name='gedansong',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
