# Generated by Django 2.0.4 on 2018-10-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20181029_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gedansong',
            name='created',
        ),
    ]
