# Generated by Django 2.0.4 on 2018-10-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20181029_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gedansong',
            name='music_albumimg',
        ),
    ]
