# Generated by Django 2.0.4 on 2018-10-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_remove_gedansong_music_albumimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gedansong',
            name='gedan',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
