# Generated by Django 2.0.4 on 2018-10-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20181029_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gedansong',
            name='gedan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gedansong', to='music.Creategedan'),
        ),
    ]
