# Generated by Django 2.0.4 on 2018-10-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20181029_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='gedansong',
            name='music_albumimg',
            field=models.TextField(blank=True),
        ),
    ]
