# Generated by Django 2.0.4 on 2018-10-29 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_gedansong_music_albumimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gedansong',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='gedansong',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
