# Generated by Django 2.0.4 on 2018-10-30 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0026_auto_20181029_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='creategedan',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='gedan_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
