# Generated by Django 2.0.4 on 2018-11-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20181031_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamiclikestates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.TextField(max_length=2)),
                ('dianzanuser', models.TextField(default='', max_length=90)),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dynamiclike', to='music.DynamicPost')),
            ],
        ),
    ]
