# Generated by Django 2.0.4 on 2018-11-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_dynamiclikestates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamiclikestates',
            name='dynamic',
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='likes',
            field=models.TextField(default='0'),
        ),
        migrations.DeleteModel(
            name='Dynamiclikestates',
        ),
    ]
