# Generated by Django 2.0.4 on 2018-11-01 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_auto_20181101_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpost',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='dynamic_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
