# Generated by Django 2.0.4 on 2018-11-01 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0033_auto_20181101_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentdynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_dynamic', to='music.DynamicPost')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator_dynamic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
